# Use python 3.8
FROM python:3.8

# Set the working directory to /my_dir
WORKDIR /my_dir

# Copy the current directory contents into the container at /my_dir
COPY . /my_dir

# Install any needed packages specified in requirements.txt
# RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME my_env_string

# Run python script when the container launches
CMD ["python", "test.py"]
